### ISSUE TITLE
sandbox can't work properly

### ISSUE THREAD

**Issue by tomhsiao1260** [danielesteban/sandbox#1]
Hi, Daniel.

Thanks in advance for your awesome work.

Actually, I'm new to WebGPU and this is my first time downloading Chrome Canary to open this application. However, seems it can't work properly on my Macbook Pro (10.15.7) as shown in screenshot below. I also tried your other works such as dots, gpuworld, gpuwater, and [this example](https://threejs.org/examples/webgpu_compute.html) from threejs community and it all work well. Any suggestion?

<img width="421" alt="img" src="https://user-images.githubusercontent.com/31985811/192152999-2f6cf0b9-29b5-44ee-b160-3c381b4f5f5e.png">

**Comment by tomhsiao1260** [comment]
Also want to ask: When it comes to making 2D sandbox or cell automata, is there any potential performance jump between WebGL and WebGPU?

btw, thanks for your tweet, Lu Wilson's design is pretty inspiring.

**Comment by danielesteban** [comment]
It looks to me like it's working in that screenshot.
You need to click and drag your mouse over the window to drop some sand to actually see something happen.
If you want it to generate a world for you, use the UI that shows up when moving your mouse over the left side of the screen and click the button that says randomize.
Also, It should work on the official chrome build. No need to use chrome canary anymore.

**Comment by danielesteban** [comment]
And as for the second question...
It depends on the implementation and requirements of the program.
But on the things I have tested so far it seems to be quite a performance boost by using WebGPU instead of WebGL even for 2D simulations.

**Comment by tomhsiao1260** [comment]
Thanks for the quick response. Not sure whether I do it correctly. I can't see any sand drop after clicking the mouse or randomize button. Here's a short film of how I use it.

https://user-images.githubusercontent.com/31985811/192155369-2fec342e-905b-47f7-a6d3-a9a16b038b21.mov

**Comment by danielesteban** [comment]
I see now.
That seems like a wgsl -> metal translation error.
You may create an issue on: https://bugs.chromium.org/p/tint/issues/list
I would do it myself but it seems to be something that only happens with your hardware/OS combination.
So it will be great if you can create it yourself and paste the console output along with the url and your OS/CPU/GPU version for the chromium people to take a look at it.

**Comment by tomhsiao1260** [comment]
Thanks for picking this up. I've sent an issue to the chrome's community. I think I can close this issue now.
https://bugs.chromium.org/p/tint/issues/detail?id=1677
